//
// Created by redalexdad on 12.12.23.
//

#ifndef MARSSTATIONASYNCHRONOUSWEBSERVICE_ASYNCHRONOUS_H
#define MARSSTATIONASYNCHRONOUSWEBSERVICE_ASYNCHRONOUS_H


class Asynchronous {

};


#endif //MARSSTATIONASYNCHRONOUSWEBSERVICE_ASYNCHRONOUS_H
